/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#94f0df',
        background: '#f3faff',
        'on-secondary-fixed-variant': '#005047',
        'on-tertiary-fixed': '#311300',
        'surface-container-highest': '#cfe6f2',
        'on-tertiary-fixed-variant': '#723600',
        'on-primary-fixed': '#001c3a',
        'on-error-container': '#93000a',
        outline: '#717783',
        'surface-dim': '#c7dde9',
        'on-tertiary-container': '#fffdff',
        'outline-variant': '#c1c6d4',
        'on-surface': '#071e27',
        'on-primary-fixed-variant': '#004786',
        'surface-container-low': '#e6f6ff',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#a5c8ff',
        'on-secondary-fixed': '#00201b',
        'secondary-fixed-dim': '#7ad7c6',
        primary: '#005dac',
        'surface-bright': '#f3faff',
        tertiary: '#934800',
        secondary: '#006b5e',
        'tertiary-fixed-dim': '#ffb786',
        'on-error': '#ffffff',
        'surface-variant': '#cfe6f2',
        'on-surface-variant': '#414752',
        'on-secondary-container': '#006f62',
        'surface-container-high': '#d5ecf8',
        'inverse-primary': '#a5c8ff',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#dff4ff',
        'error-container': '#ffdad6',
        'surface-tint': '#005faf',
        surface: '#f3faff',
        'primary-fixed': '#d4e3ff',
        error: '#ba1a1a',
        'tertiary-fixed': '#ffdcc6',
        'secondary-fixed': '#97f3e2',
        'primary-container': '#1976d2',
        'on-primary-container': '#fffdff',
        'on-background': '#071e27',
        'inverse-surface': '#1e333c',
        'surface-container': '#dbf1fe',
        'tertiary-container': '#b85c00',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      maxWidth: {
        container: '1200px',
      },
      boxShadow: {
        soft: '0 18px 60px rgba(34, 49, 63, 0.12)',
      },
    },
  },
  plugins: [],
};
